
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // Use a dummy URL for generation if DATABASE_URL is not set
    // Prisma generation doesn't actually connect to the database
    url: env("DATABASE_URL") || "postgresql://dummy:dummy@localhost:5432/dummy",
  },
});
